package com.csipl.hrms.service.common;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

import com.csipl.hrms.service.common.repository.FcmNotificationRepository;


@Service("pushNotificationsServices")
public class PushNotificationsServiceImpl implements PushNotificationsServices{
    

	@Autowired
	FcmNotificationRepository fcmNotificationRepository;
	
	 @Autowired
	  PushNotificationsService androidPushNotificationsService;
	 
	@Override
	public ArrayList<String> getReportingEmployeeCode(Long employeeId) {
		Long reportingUserId = fcmNotificationRepository.getEmpReportingToUserId(employeeId);
		ArrayList<String> tokenList = fcmNotificationRepository.getTokenList(reportingUserId);
		return tokenList;
	}
		 
	/* PARAMETER DESCRIPTION 
		 * registration_ids : contains list of token generated by FIREBASE
		 * title : contains heading of notification
		 * MESSAGE : contains body of notification
		 * notificationType : contains type of notification weather it is AR , Leave ,separation
		 * applyId : contains unique key of msg object regarding leave ,AR..
		 * nevigationFlag : flag for android by this in android flow goes to particular screen
		 */
	  public ResponseEntity<String> fcmRequest(ArrayList<String> registration_ids , String title , String message,
			                                           String notificationType,Long applyId , String nevigationFlag)   throws JSONException{
		
		    JSONObject body = new JSONObject();
		    /////body.put("to", token);
		    body.put("registration_ids", new JSONArray(registration_ids));
		    body.put("priority", "high");
		    
		    JSONObject data = new JSONObject();
		    data.put("title", title);
		    data.put("body", message);
		    data.put("type", notificationType);
		    data.put("applyId", applyId);
		    data.put("nevigationFlag", nevigationFlag);
		    
		    body.put("data", data);
		    
		    HttpEntity<String> request = new HttpEntity<>(body.toString());
		
		 
		    CompletableFuture<String> pushNotification = androidPushNotificationsService.send(request);
		    CompletableFuture.allOf(pushNotification).join();
		    
		    try {
		      String firebaseResponse = pushNotification.get();
		      return new ResponseEntity<>(firebaseResponse, HttpStatus.OK);
		    } catch (InterruptedException e) {
		     // e.printStackTrace();
		    } catch (ExecutionException e) {
		     // e.printStackTrace();
		    }
		    
		    return new ResponseEntity<>("FCM Push Notification ERROR!", HttpStatus.BAD_REQUEST);
		  }
	  
	  
	  public ResponseEntity<String> fcmRequestforCheckIO( String title , String message,
              String notificationType,Long applyId , String nevigationFlag)   throws JSONException{

		  JSONObject body = new JSONObject();
		  body.put("to", "/topics/nc");
		  body.put("priority", "high");

		  JSONObject data = new JSONObject();
		  data.put("title", title);
		  data.put("body", message);
		  data.put("type", notificationType);
		  data.put("applyId", applyId);
		  data.put("nevigationFlag", nevigationFlag);

		  body.put("data", data);

		  HttpEntity<String> request = new HttpEntity<>(body.toString());


		  CompletableFuture<String> pushNotification = androidPushNotificationsService.send(request);
		  CompletableFuture.allOf(pushNotification).join();

		  try {
			  String firebaseResponse = pushNotification.get();
			  return new ResponseEntity<>(firebaseResponse, HttpStatus.OK);
		  } catch (InterruptedException e) {
			 // e.printStackTrace();
		  } catch (ExecutionException e) {
			 // e.printStackTrace();
		  }

		  return new ResponseEntity<>("FCM Push Notification ERROR!", HttpStatus.BAD_REQUEST);
	  	}
	}



